services:

  backend:
    build: .
    restart: unless-stopped

    command: >
      sh -c "
      python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 project_adhd.asgi:application
      "

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  mysql_data: