# Generated by Django 5.0.6 on 2025-03-29 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessmentQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='modified_date')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=50, verbose_name='Status')),
                ('question_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Question Text')),
                ('category', models.CharField(blank=True, choices=[('INATTENTION_SYMPTOMS', 'Inattention Symptoms'), ('HYPERACTIVE_SYMPTOMS', 'Hyperactive Symptoms'), ('IMPULSIVE_SYMPTOMS', 'Impulsive Symptoms'), ('PARENT_CHECKLIST', 'PARENT_CHECKLIST')], default='HYPERACTIVE_SYMPTOMS', max_length=300, null=True, verbose_name='Question Category')),
                ('is_for_adults', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SelfAssessmentQuestions',
                'verbose_name_plural': 'SelfAssessmentQuestions',
                'db_table': 'SelfAssessmentQuestions',
            },
        ),
        migrations.CreateModel(
            name='SelfAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, choices=[('NOT_AT_ALL', 'Not at all'), ('JUST_A_LITTLE', 'Just a Little'), ('OFTEN', 'Often'), ('VERY_OFTEN', 'Very Often')], default='JUST_A_LITTLE', max_length=300, null=True, verbose_name='Response')),
                ('text_response', models.TextField(blank=True, null=True, verbose_name='Text Response')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesment_question', to='assessment.selfassessmentquestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesment_completed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SelfAssessmentResponse',
                'verbose_name_plural': 'SelfAssessmentResponse',
                'db_table': 'SelfAssessmentResponse',
            },
        ),
    ]
