# Generated by Django 5.0.6 on 2025-03-29 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassessmentresponse',
            name='user',
        ),
        migrations.AlterField(
            model_name='selfassessmentresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesment_question', to='assessment.selfassessmentquestions'),
        ),
        migrations.CreateModel(
            name='SelfAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=300, null=True, verbose_name='Result')),
                ('inattention_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Self Inattention Score')),
                ('hyperactive_impulsive_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Self Hyperactive/Impulsive Score')),
                ('diagnosed_inattention', models.BooleanField(default=False, verbose_name='Diagnosed with Inattention')),
                ('diagnosed_hyperactive_impulsive', models.BooleanField(default=False, verbose_name='Diagnosed with Hyperactivity/Impulsivity')),
                ('diagnosed_combined_adhd', models.BooleanField(default=False, verbose_name='Diagnosed with Combined ADHD')),
                ('requires_parent_checklist', models.BooleanField(default=False, verbose_name='Requires Parent Checklist')),
                ('parent_inattention_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Parent-Reported Inattention Score')),
                ('parent_hyperactive_impulsive_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Parent-Reported Hyperactive/Impulsive Score')),
                ('parent_confirms_inattention', models.BooleanField(default=False, verbose_name='Parent Confirms Inattention')),
                ('parent_confirms_hyperactive_impulsive', models.BooleanField(default=False, verbose_name='Parent Confirms Hyperactivity/Impulsivity')),
                ('parent_confirms_combined_adhd', models.BooleanField(default=False, verbose_name='Parent Confirms Combined ADHD')),
                ('confirms_adhd', models.BooleanField(default=False, verbose_name='User Have ADHD')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesment_completed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SelfAssessmentResult',
                'verbose_name_plural': 'SelfAssessmentResult',
                'db_table': 'SelfAssessmentResult',
            },
        ),
        migrations.AddField(
            model_name='selfassessmentresponse',
            name='result_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_for_response', to='assessment.selfassessmentresult'),
        ),
    ]
