# Generated by Django 5.0.6 on 2025-03-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_selfassessmentresponse_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessmentquestions',
            name='is_parent_checklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='selfassessmentquestions',
            name='category',
            field=models.CharField(blank=True, choices=[('INATTENTION_SYMPTOMS', 'Inattention Symptoms'), ('HYPERACTIVE_SYMPTOMS', 'Hyperactive Symptoms'), ('IMPULSIVE_SYMPTOMS', 'Impulsive Symptoms')], default='HYPERACTIVE_SYMPTOMS', max_length=300, null=True, verbose_name='Question Category'),
        ),
    ]
