# Generated by Django 5.0.6 on 2025-04-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_selfassessmentquestions_is_parent_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassessmentresponse',
            name='response',
            field=models.CharField(blank=True, choices=[('0', 'Not at all'), ('1', 'Just a Little'), ('2', 'Often'), ('3', 'Very Often')], default='1', max_length=300, null=True, verbose_name='Response'),
        ),
    ]
