# Generated by Django 5.0.6 on 2025-06-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_selfassessmentresponse_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADHDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, storage='/adhd', upload_to='')),
            ],
        ),
    ]
