# Generated by Django 5.0.6 on 2025-06-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_adhddocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhddocument',
            options={'verbose_name': 'ADHDDocument', 'verbose_name_plural': 'ADHDDocument'},
        ),
        migrations.AlterModelTable(
            name='adhddocument',
            table='ADHDDocument',
        ),
    ]
