# Generated by Django 5.0.6 on 2025-06-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_adhddocument_options_alter_adhddocument_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhddocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document Name'),
        ),
    ]
