# Generated by Django 5.0.6 on 2025-06-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_adhddocument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhddocument',
            name='file',
            field=models.FileField(null=True, upload_to='adhd'),
        ),
    ]
