# Generated by Django 5.0.6 on 2025-11-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_alter_adhddocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassessmentquestions',
            name='is_parent_checklist',
        ),
        migrations.AddField(
            model_name='selfassessmentquestions',
            name='category_num',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Category Number'),
        ),
        migrations.AlterField(
            model_name='selfassessmentquestions',
            name='category',
            field=models.CharField(blank=True, choices=[('RF', 'Reading Focus'), ('VT', 'Visual Tracking'), ('AL', 'Auditory/Listening'), ('SR', 'Self Regulation'), ('N', 'Reverse Scored')], default='N', max_length=300, null=True, verbose_name='Question Category'),
        ),
    ]
