# Generated by Django 5.0.6 on 2025-11-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_remove_selfassessmentquestions_is_parent_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='parent_confirms_combined_adhd',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='parent_confirms_hyperactive_impulsive',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='parent_confirms_inattention',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='parent_hyperactive_impulsive_score',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='parent_inattention_score',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='requires_parent_checklist',
        ),
        migrations.AlterField(
            model_name='selfassessmentresponse',
            name='response',
            field=models.CharField(blank=True, choices=[('0', 'Never'), ('1', 'Rarely'), ('2', 'Sometimes'), ('3', 'Often'), ('4', 'Very Often')], default='0', max_length=300, null=True, verbose_name='Response'),
        ),
    ]
