# Generated by Django 5.0.6 on 2025-11-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_remove_selfassessmentresult_parent_confirms_combined_adhd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='confirms_adhd',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='diagnosed_combined_adhd',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='diagnosed_hyperactive_impulsive',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='diagnosed_inattention',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='hyperactive_impulsive_score',
        ),
        migrations.RemoveField(
            model_name='selfassessmentresult',
            name='inattention_score',
        ),
        migrations.AddField(
            model_name='selfassessmentresult',
            name='audio_listening_total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='AL Total Score'),
        ),
        migrations.AddField(
            model_name='selfassessmentresult',
            name='program_duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Program Duration'),
        ),
        migrations.AddField(
            model_name='selfassessmentresult',
            name='raw_total',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Raw Total Score'),
        ),
        migrations.AddField(
            model_name='selfassessmentresult',
            name='read_focus_total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='RF Total Score'),
        ),
        migrations.AddField(
            model_name='selfassessmentresult',
            name='tenscore',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total Score In Ten'),
        ),
        migrations.AddField(
            model_name='selfassessmentresult',
            name='visual_tracking_total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='VT Total Score'),
        ),
    ]
