# Generated by Django 5.2.14 on 2026-06-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_assessment_read_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='selfassessmentquestions',
            new_name='SelfAssessm_is_for__dfd489_idx',
            old_name='SelfAssess_is_for__e0aeaa_idx',
        ),
        migrations.RenameIndex(
            model_name='selfassessmentresponse',
            new_name='SelfAssessm_result__00eb51_idx',
            old_name='SelfAssess_result__496fad_idx',
        ),
        migrations.RenameIndex(
            model_name='selfassessmentresult',
            new_name='SelfAssessm_user_id_db89a1_idx',
            old_name='SelfAssess_user_id_1b79e0_idx',
        ),
    ]
