# Generated by Django 5.0.6 on 2025-12-14 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(blank=True, null=True, verbose_name='Day Number')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProgressTracker',
                'verbose_name_plural': 'ProgressTracker',
                'db_table': 'ProgressTracker',
            },
        ),
        migrations.CreateModel(
            name='UserAssessmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_duration', models.IntegerField(blank=True, null=True, verbose_name='Course Duration Days')),
                ('last_completed', models.IntegerField(blank=True, null=True, verbose_name='Last Completed Day')),
                ('started_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Course Started On')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserAssessmentDetails',
                'verbose_name_plural': 'UserAssessmentDetails',
                'db_table': 'UserAssessmentDetails',
            },
        ),
    ]
