# Generated by Django 5.0.6 on 2026-01-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresstracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresstracker',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('audio', 'Audio')], max_length=50, null=True, verbose_name='File Type'),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='is_day_completed',
            field=models.BooleanField(default=False, verbose_name='Is Day Completed'),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='userassessmentdetails',
            name='is_day_completed',
            field=models.BooleanField(default=False, verbose_name='Is Day Completed'),
        ),
    ]
