# Generated by Django 5.0.6 on 2026-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresstracker', '0002_remove_progresstracker_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstracker',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('file', 'File')], max_length=50, null=True, verbose_name='File Type'),
        ),
    ]
