# Generated by Django 5.0.6 on 2026-02-03 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresstracker', '0003_alter_progresstracker_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAttentionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('concentration_score', models.FloatField()),
                ('gaze_ratio_avg', models.FloatField(default=1.0)),
                ('inattention_duration', models.FloatField(default=0.0)),
                ('drowsy_state', models.FloatField(default=0.2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
