# Generated by Codex on 2026-07-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'StripeWebhookEvent',
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StripeCustomer',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused'), ('deleted', 'Deleted')], db_index=True, max_length=50)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, db_index=True, max_length=50)),
                ('hosted_invoice_url', models.URLField(blank=True, max_length=500, null=True)),
                ('invoice_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PaymentInvoice',
            },
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['event_type', 'created_at'], name='StripeWebho_event_t_da87af_idx'),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['processed', 'created_at'], name='StripeWebho_process_3e69e6_idx'),
        ),
        migrations.AddIndex(
            model_name='stripecustomer',
            index=models.Index(fields=['user'], name='StripeCusto_user_id_78e8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='stripecustomer',
            index=models.Index(fields=['stripe_customer_id'], name='StripeCusto_stripe__211d28_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='Subscriptio_user_id_c3db21_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='Subscriptio_status_a6bc1c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='Subscriptio_stripe__a2fba5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinvoice',
            index=models.Index(fields=['user', 'created_at'], name='PaymentInvo_user_id_45f43f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinvoice',
            index=models.Index(fields=['status'], name='PaymentInvo_status_335546_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinvoice',
            index=models.Index(fields=['stripe_subscription_id'], name='PaymentInvo_stripe__5a8066_idx'),
        ),
    ]
