# Generated by Django 5.2 on 2026-08-10
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('payments', '0001_initial')]
    operations = [
        # Remove the retired Stripe models from Django's state while retaining
        # their historical database tables/data for a reversible rollout.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='PaymentInvoice'),
                migrations.DeleteModel(name='StripeWebhookEvent'),
                migrations.DeleteModel(name='Subscription'),
                migrations.DeleteModel(name='StripeCustomer'),
            ],
        ),
        migrations.CreateModel(
            name='StoreNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('event_id', models.CharField(max_length=512)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'db_table': 'StoreNotificationEvent'},
        ),
        migrations.CreateModel(
            name='StorePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('product_id', models.CharField(db_index=True, max_length=255)),
                ('store_purchase_id', models.CharField(max_length=512)),
                ('original_transaction_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('latest_transaction_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('environment', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace_period', 'Grace period'), ('paused', 'Paused'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('revoked', 'Revoked'), ('pending', 'Pending')], db_index=True, max_length=30)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auto_renewing', models.BooleanField(default=False)),
                ('is_restore', models.BooleanField(default=False)),
                ('raw_verification_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'StorePurchase'},
        ),
        migrations.CreateModel(
            name='SubscriptionEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('product_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace_period', 'Grace period'), ('paused', 'Paused'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('revoked', 'Revoked'), ('pending', 'Pending')], db_index=True, max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='payments.storepurchase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_entitlement', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'SubscriptionEntitlement'},
        ),
        migrations.AddConstraint(model_name='storenotificationevent', constraint=models.UniqueConstraint(fields=('platform', 'event_id'), name='uniq_store_notification_event')),
        migrations.AddConstraint(model_name='storepurchase', constraint=models.UniqueConstraint(fields=('platform', 'store_purchase_id'), name='uniq_store_purchase_evidence')),
        migrations.AddIndex(model_name='storepurchase', index=models.Index(fields=['user', 'status'], name='StorePurcha_user_id_0097b8_idx')),
        migrations.AddIndex(model_name='storepurchase', index=models.Index(fields=['platform', 'original_transaction_id'], name='StorePurcha_platfor_395000_idx')),
    ]
