# Generated by Django 5.0.6 on 2025-03-16 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='User Name')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Login')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Avg Rating')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='modified_date')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=50, verbose_name='Status')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Role Name')),
                ('category', models.CharField(choices=[('RDA', 'RDA'), ('DFI', 'DFI'), ('OM', 'OM')], default='RDA', max_length=50, verbose_name='Role Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Role Description')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='Is Deletable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles_permission', to='auth.permission', verbose_name='Roles Permission')),
            ],
            options={
                'verbose_name': 'Roles',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
    ]
