# Generated by Django 5.0.6 on 2025-03-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='dob'),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=50, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='users',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='users',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
