# Generated by Django 5.0.6 on 2025-03-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_avg_rating_users_country_users_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='dob'),
        ),
    ]
