# Generated by Django 5.0.6 on 2026-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetotp_delete_generatedotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ai_assessment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='AI Assessment Score'),
        ),
    ]
