# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='OTP Hash'),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Reset Token Hash'),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Used At'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
