# Generated by Codex on 2026-07-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_secure_password_reset_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=50, verbose_name='Provider')),
                ('provider_subject', models.CharField(max_length=255, verbose_name='Provider Subject')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to='users.users')),
            ],
            options={
                'verbose_name': 'OAuth Account',
                'verbose_name_plural': 'OAuth Accounts',
                'db_table': 'OAuthAccount',
            },
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['user', 'provider'], name='OAuthAccoun_user_id_58db21_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['email'], name='OAuthAccoun_email_0f6f42_idx'),
        ),
        migrations.AddConstraint(
            model_name='oauthaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_subject'), name='uniq_oauth_provider_subject'),
        ),
    ]
