# Generated by Django 5.2.14 on 2026-07-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_oauthaccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='oauthaccount',
            new_name='OAuthAccoun_user_id_70a8db_idx',
            old_name='OAuthAccoun_user_id_58db21_idx',
        ),
        migrations.RenameIndex(
            model_name='oauthaccount',
            new_name='OAuthAccoun_email_f6e18a_idx',
            old_name='OAuthAccoun_email_0f6f42_idx',
        ),
    ]
