# Generated by Codex on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_users_is_first_users_is_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthaccount',
            name='provider',
            field=models.CharField(
                choices=[
                    ('google', 'Google'),
                    ('facebook', 'Facebook'),
                    ('apple', 'Apple'),
                ],
                max_length=50,
                verbose_name='Provider',
            ),
        ),
    ]
