# Generated by Django 5.2.14 on 2026-06-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_list_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_status_f9f737_idx',
            old_name='articles_status_905de7_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='articles_status_46c6b8_idx',
            old_name='articles_status_71cabc_idx',
        ),
    ]
