"""
Django settings for alcan project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os,dj_database_url # type: ignore
from pathlib import Path
from dotenv import load_dotenv, find_dotenv
import datetime
from decouple import config
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ImproperlyConfigured

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from boto3.s3.transfer import TransferConfig
from botocore.config import Config

SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0,
        send_default_pii=True
    )


import environ

GOOGLE_OAUTH_CLIENT_IDS = [
    client_id.strip()
    for client_id in config('GOOGLE_OAUTH_CLIENT_IDS', default='').split(',')
    if client_id.strip()
]
FACEBOOK_APP_ID = config('FACEBOOK_APP_ID', default='')
env = environ.Env(
    DEBUG=(bool, False),
)
load_dotenv(find_dotenv(), override=True, verbose=True)

DJANGO_ENV = config('DJANGO_ENV', default=os.environ.get('DJANGO_ENV', 'development')).lower()
IS_PRODUCTION = DJANGO_ENV in {'prod', 'production'}

def get_secret_config(key, *, default=None, aliases=()):
    value = config(key, default=None)
    for alias in aliases:
        if value:
            break
        value = config(alias, default=None)
    if IS_PRODUCTION and not value:
        raise ImproperlyConfigured(f"{key} must be set when DJANGO_ENV=production")
    return value if value is not None else default

FACEBOOK_APP_SECRET = get_secret_config('FACEBOOK_APP_SECRET', default='')

def get_env_value(key,default=None):
    try:
        return env(key, default=default)
    except environ.ImproperlyConfigured:
        return os.environ.get(key, default)



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret_config('SECRET_KEY', default='dev-only-insecure-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_value('DEBUG', False)

ALLOWED_HOSTS = [
    host.strip()
    for host in config("ALLOWED_HOSTS", default="localhost,127.0.0.1,13.217.234.177").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in config("CSRF_TRUSTED_ORIGINS", default="https://13.217.234.177").split(",")
    if origin.strip()
]

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in config("CORS_ALLOWED_ORIGINS", default="https://13.217.234.177").split(",")
    if origin.strip()
]

X_FRAME_OPTIONS = 'ALLOWALL'

SECURE_CONTENT_TYPE_NOSNIFF = True
CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

ASGI_APPLICATION = 'project_adhd.asgi.application'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# Application definitionaaa

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

LOCAL_APPS = [
    'apps.authentication',
    'apps.users',
    'apps.assessment',
    'apps.websocket',
    'apps.filehandler',
    'apps.progresstracker',
    'apps.articles',
    'apps.payments',
]


INTERNAL_IPS = [
    "127.0.0.1",
]

THIRD_PARTY_APPS = [
    'drf_yasg',
    'debug_toolbar',
    'django_extensions',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'storages',
    'channels',
    'import_export',
]

INSTALLED_APPS = INSTALLED_APPS + LOCAL_APPS  + THIRD_PARTY_APPS

UNFOLD = {
    "SITE_TITLE": "ADHD Minder",
    "SITE_HEADER": "ADHD Minder",
    "SITE_SUBHEADER": "Operations Console",
    "SITE_SYMBOL": "psychology",
    "SITE_URL": "/api/docs/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "BORDER_RADIUS": "8px",
    "DASHBOARD_CALLBACK": "project_adhd.admin_dashboard.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Core"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Users"),
                        "icon": "group",
                        "link": reverse_lazy("admin:users_users_changelist"),
                    },
                    {
                        "title": _("Assessments"),
                        "icon": "quiz",
                        "link": reverse_lazy("admin:assessment_selfassessmentquestions_changelist"),
                    },
                    {
                        "title": _("Progress"),
                        "icon": "monitoring",
                        "link": reverse_lazy("admin:progresstracker_progresstracker_changelist"),
                    },
                ],
            },
            {
                "title": _("Content"),
                "separator": True,
                "items": [
                    {
                        "title": _("Articles"),
                        "icon": "article",
                        "link": reverse_lazy("admin:articles_article_changelist"),
                    },
                    {
                        "title": _("ADHD Content"),
                        "icon": "folder_open",
                        "link": reverse_lazy("admin:filehandler_adhdcontent_changelist"),
                    },
                    {
                        "title": _("Documents"),
                        "icon": "description",
                        "link": reverse_lazy("admin:assessment_adhddocument_changelist"),
                    },
                ],
            },
            {
                "title": _("Insights"),
                "separator": True,
                "items": [
                    {
                        "title": _("Attention Sessions"),
                        "icon": "visibility",
                        "link": reverse_lazy("admin:progresstracker_faceattentionsession_changelist"),
                    },
                    {
                        "title": _("Feedback"),
                        "icon": "reviews",
                        "link": reverse_lazy("admin:filehandler_feedbackreview_changelist"),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'project_adhd.middleware.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'project_adhd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# AUDITLOG_INCLUDE_ALL_MODELS=True


WSGI_APPLICATION = 'project_adhd.wsgi.application'

AUTH_USER_MODEL = 'users.Users'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASE_ENGINE = config('DATABASE_ENGINE', default='sqlite').lower()

# if DATABASE_ENGINE == 'postgres':
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='truefoxai_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': get_secret_config('DATABASE_PASSWORD', aliases=('DB_PASSWORD',), default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_CACHE_URL", default="redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "adhd"
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AWS_LOCATION = 'media'
AWS_PRIVATE_MEDIA_LOCATION = 'private'

# Static files (CSS, JavaScript, etc.)
STATIC_URL = '/assets/'  # URL prefix for static files
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')  # Where static files will be collected by collectstatic

# Add additional locations of static files (e.g., static directory in your project)
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),  # Update to a cleaner BASE_DIR usage
)

AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default="s-adhd")
AWS_S3_REGION_NAME = 'us-east-1' 
# These are important for avoiding signature issues
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'virtual'
AWS_S3_USE_SSL = True
AWS_S3_VERIFY = True
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = True
AWS_S3_FILE_OVERWRITE = False
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
AWS_S3_MAX_MEMORY_SIZE = 100 * 1024 * 1024
AWS_S3_TRANSFER_CONFIG = TransferConfig(
    multipart_threshold=64 * 1024 * 1024,
    multipart_chunksize=16 * 1024 * 1024,
    max_concurrency=10,
    use_threads=True,
)
AWS_S3_CLIENT_CONFIG = Config(
    signature_version=AWS_S3_SIGNATURE_VERSION,
    s3={"addressing_style": AWS_S3_ADDRESSING_STYLE},
    max_pool_connections=20,
    connect_timeout=60,
    read_timeout=300,
    retries={"max_attempts": 5, "mode": "standard"},
)

# Media files are stored on S3 through django-storages. MEDIA_ROOT is kept only
# as a temporary upload directory for Django's upload handlers, not as the final
# media storage location.
MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/{AWS_LOCATION}/"
MEDIA_ROOT = os.path.join(BASE_DIR, "tmp_uploads")
FILE_UPLOAD_TEMP_DIR = MEDIA_ROOT
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 1100 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = config('DATA_UPLOAD_MAX_NUMBER_FIELDS', default=50000, cast=int)

STORAGES = {
    "default": {
        "BACKEND": "project_adhd.storage_backends.LargeMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/api/docs'


SWAGGER_SETTINGS = {
    'DEFAULT_API_URL' : os.environ.get('SWAGGER_DEFAULT_API_URL', ""),
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },

}

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'helpers.exceptions.exceptions.handle_exception',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 2,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTTokenUserAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day'
    }
}


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'helpers.utils.auth_handler.UserCustomAuthenticator'
]


ATOMIC_REQUESTS=True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=20),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=50),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': get_secret_config('JWT_SIGNING_KEY', aliases=('JWT_SECRET_KEY',), default='dev-only-insecure-jwt-signing-key'),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': datetime.timedelta(days=20),
    'SLIDING_TOKEN_REFRESH_LIFETIME': datetime.timedelta(days=50),
}

EMAIL_BACKEND         = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST            = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_HOST_USER       = config('EMAIL_HOST_USER', default='testmailadhd@gmail.com')
EMAIL_HOST_PASSWORD   = get_secret_config('EMAIL_HOST_PASSWORD', default='')
EMAIL_PORT            = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS         = True
DEFAULT_FROM_EMAIL    = config('DEFAULT_FROM_EMAIL', default='testmailadhd@gmail.com')

STRIPE_SECRET_KEY = get_secret_config('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = get_secret_config('STRIPE_WEBHOOK_SECRET', default='')
STRIPE_MONTHLY_PRICE_ID = config('STRIPE_MONTHLY_PRICE_ID', default='')
STRIPE_SUCCESS_URL = config('STRIPE_SUCCESS_URL', default='')
STRIPE_CANCEL_URL = config('STRIPE_CANCEL_URL', default='')
STRIPE_BILLING_PORTAL_RETURN_URL = config('STRIPE_BILLING_PORTAL_RETURN_URL', default='')
PAYMENT_APP_SUCCESS_URL = config('PAYMENT_APP_SUCCESS_URL', default='attentionminder://payments/success')
PAYMENT_APP_CANCEL_URL = config('PAYMENT_APP_CANCEL_URL', default='attentionminder://payments/cancel')
STRIPE_ALLOWED_REDIRECT_HOSTS = [
    host.strip()
    for host in config('STRIPE_ALLOWED_REDIRECT_HOSTS', default='').split(',')
    if host.strip()
]


import firebase_admin
from firebase_admin import credentials
cred = credentials.Certificate(config('FIREBASE_CREDENTIALS_PATH', default='files/attentionminder-3f4d6-firebase-adminsdk-fbsvc-704503bc6e.json'))
firebase_admin.initialize_app(cred)

# Celery Configuration Options
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/2')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/2')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

