from rest_framework import serializers
from apps.assessment.models import SelfAssessmentResponse,SelfAssessmentResult,SelfAssessmentQuestions
from apps.assessment.services.assessment_service import AssessmentService
from apps.filehandler.models import AdhdContent
from apps.progresstracker.models import (
    FaceAttentionSession,
    generate_attention_session_id,
)
from apps.progresstracker.services.track_services import ProgressTrackerActions
from apps.assessment.cache import bump_user_management_cache
from django.db import transaction
from helpers.helper import get_token_user_or_none,get_object_or_none
from rest_framework.exceptions import ValidationError
import math


"""Self Assessment Serializers"""


"""Self Assessment Serializers"""

class SelfAssessmentSubSerializer(serializers.ModelSerializer):
    question        = serializers.IntegerField(allow_null=False, required=True)
    response        = serializers.ChoiceField(choices=SelfAssessmentResponse.RESPONSE_CHOICES.choices,allow_null=False, required=False)
    answer          = serializers.ChoiceField(choices=SelfAssessmentResponse.RESPONSE_CHOICES.choices,allow_null=False, required=False, write_only=True)
    text_response   = serializers.CharField(allow_null=True, required=False)

    class Meta:
        model = SelfAssessmentResponse
        fields = ['id','question','response','answer','text_response']

    def validate(self,attrs):
        answer = attrs.pop('answer', None)
        if attrs.get('response') in (None, '') and answer not in (None, ''):
            attrs['response'] = answer

        if attrs.get('response') in (None, ''):
            raise ValidationError({'response': 'This field is required.'})

        question_instance = get_object_or_none(SelfAssessmentQuestions,pk=attrs.get('question'))
        if question_instance is None:
            raise ValidationError({'question': 'Invalid question id.'})
        if not question_instance.is_active:
            raise ValidationError({'question': 'Question is not active.'})

        request = self.context.get('request') or getattr(self.root, 'context', {}).get('request')
        user_instance = get_token_user_or_none(request) if request else None
        if user_instance and question_instance.is_for_adults != bool(user_instance.adult):
            raise ValidationError({'question': 'Question does not match current user age group.'})

        attrs['_question_instance'] = question_instance
        return attrs
    
    def create(self,validated_data):
        result_instance = self.context.get('result_instance',None)

        question_instance = validated_data.pop('_question_instance', None)
        if question_instance is None:
            question_instance = get_object_or_none(SelfAssessmentQuestions,pk=validated_data.get('question'))
        if question_instance is None:
            raise ValidationError({'question': 'Invalid question id.'})

        instance = SelfAssessmentResponse.objects.filter(result_entry=result_instance,question=question_instance).first()

        if instance:
            instance.response = validated_data.get('response')
            instance.text_response = validated_data.get('text_response', None)
            instance.save(update_fields=['response', 'text_response'])
            return instance

        instance                = SelfAssessmentResponse()
        instance.result_entry   = result_instance
        instance.question       = question_instance
        instance.response       = validated_data.get('response')
        instance.text_response  = validated_data.get('text_response',None)
        instance.save()

        return instance


class SelfAssessmentResponseSerializer(serializers.ModelSerializer):
    assesment   = serializers.ListField(child=SelfAssessmentSubSerializer(),allow_empty=False)

    class Meta:
        model = SelfAssessmentResult
        fields = ['assesment']


    def validate(self, attrs):
        return super().validate(attrs)


    def create(self, validated_data):
        request = self.context.get('request',None)

        assessment_results = validated_data.get('assesment',[])
        user_instance = get_token_user_or_none(request)


        instance = AssessmentService.get_or_create_result_for_user(user_instance)

        for results in assessment_results:
            sub_serializer = SelfAssessmentSubSerializer(context={'request':request,'result_instance':instance})
            sub_serializer.create(results)

        is_adult = bool(user_instance.adult)

        instance = AssessmentService.calculate_result(instance, is_adult)

        return instance


class FiniteFloatField(serializers.FloatField):
    def to_internal_value(self, data):
        value = super().to_internal_value(data)
        if not math.isfinite(value):
            raise ValidationError('A finite number is required.')
        return value


class FrontendAttentionScoreSerializer(serializers.Serializer):
    # The attention score is generated by the frontend and stored as
    # self-reported telemetry; backend validation only checks shape/ranges.
    session_id = serializers.CharField(required=False, allow_blank=False, max_length=100)
    content_type = serializers.CharField(required=False, allow_blank=False, max_length=50)
    file_id = serializers.PrimaryKeyRelatedField(
        source='file',
        queryset=AdhdContent.objects.all(),
        required=True,
        allow_null=False,
    )
    is_assessment = serializers.BooleanField(required=True)
    calculation_version = serializers.CharField(required=False, allow_blank=False, max_length=100)
    final_score = FiniteFloatField(required=True, min_value=0, max_value=100)
    attention_engagement_rate = FiniteFloatField(required=True, min_value=0, max_value=100)
    reading_engagement_rate = FiniteFloatField(required=False, min_value=0, max_value=100, default=0)
    average_confidence = FiniteFloatField(required=True, min_value=0, max_value=1)
    total_processed_frames = serializers.IntegerField(required=True, min_value=0)
    sampled_frames = serializers.IntegerField(required=True, min_value=0)
    reading_focused_frames = serializers.IntegerField(required=False, min_value=0, default=0)
    watching_video_frames = serializers.IntegerField(required=False, min_value=0, default=0)
    idle_distracted_frames = serializers.IntegerField(required=False, min_value=0, default=0)
    session_duration_seconds = FiniteFloatField(required=True, min_value=0)
    inattention_duration = FiniteFloatField(required=True, min_value=0)
    maximum_inattention_duration = FiniteFloatField(required=False, min_value=0, default=0)
    gaze_ratio_avg = FiniteFloatField(required=True, min_value=0, max_value=1)
    gaze_quality_avg = FiniteFloatField(required=False, min_value=0, max_value=1, default=0)
    reading_gaze_frequency_avg_hz = FiniteFloatField(required=False, min_value=0, default=0)
    reading_gaze_amplitude_avg = FiniteFloatField(required=False, min_value=0, default=0)
    drowsy_state = FiniteFloatField(required=True, min_value=0, max_value=1)
    brightness_score = FiniteFloatField(required=True, min_value=0, max_value=100)
    pitch = FiniteFloatField(required=True, min_value=-180, max_value=180)
    yaw = FiniteFloatField(required=True, min_value=-180, max_value=180)
    roll = FiniteFloatField(required=True, min_value=-180, max_value=180)
    blink_ratio = FiniteFloatField(required=True, min_value=0)
    yawn_distance = FiniteFloatField(required=True, min_value=0)
    bad_frame_count = serializers.IntegerField(required=True, min_value=0)
    blurry_frame_count = serializers.IntegerField(required=True, min_value=0)
    low_light_frame_count = serializers.IntegerField(required=True, min_value=0)
    eyes_closed_count = serializers.IntegerField(required=True, min_value=0)
    gaze_warning_count = serializers.IntegerField(required=True, min_value=0)

    def validate(self, attrs):
        unknown_fields = set(self.initial_data.keys()) - set(self.fields.keys())
        if unknown_fields:
            raise ValidationError({
                field: 'Unknown field.' for field in sorted(unknown_fields)
            })

        user = self.context['request'].user
        content = attrs['file']
        if content.is_management:
            age_group = user.age_category or 'adult'
            if content.age_group != age_group:
                raise ValidationError({
                    'file_id': "Lesson/file does not belong to this user's age group."
                })

            unlocked_days = ProgressTrackerActions.get_days_for_the_file(user) or [1]
            if content.day not in unlocked_days:
                raise ValidationError({
                    'file_id': 'Lesson/file is locked for this user.'
                })

        expected_average_score = round((attrs['final_score'] / 100.0) * 8.0, 2)
        attrs['average_concentration_score'] = expected_average_score
        attrs['concentration_score'] = expected_average_score

        if attrs['sampled_frames'] > attrs['total_processed_frames']:
            raise ValidationError({
                'sampled_frames': 'Cannot exceed total_processed_frames.'
            })

        frame_breakdown_total = (
            attrs['reading_focused_frames']
            + attrs['watching_video_frames']
            + attrs['idle_distracted_frames']
        )
        if frame_breakdown_total > attrs['sampled_frames']:
            raise ValidationError({
                'reading_focused_frames': 'Reading/video/idle frame total cannot exceed sampled_frames.'
            })

        if attrs['inattention_duration'] > attrs['session_duration_seconds']:
            raise ValidationError({
                'inattention_duration': 'Cannot exceed session_duration_seconds.'
            })

        if attrs['maximum_inattention_duration'] > attrs['session_duration_seconds']:
            raise ValidationError({
                'maximum_inattention_duration': 'Cannot exceed session_duration_seconds.'
            })

        return attrs

    def create(self, validated_data):
        # User ownership is always taken from the authenticated JWT user.
        # Clients must not choose or spoof a user_id in telemetry payloads.
        user = self.context['request'].user
        final_score = validated_data.get('final_score')
        session_id = validated_data.get('session_id') or generate_attention_session_id()
        validated_data['session_id'] = session_id
        validated_data['content_type'] = validated_data.get(
            'content_type',
            validated_data['file'].file_type if validated_data.get('file') else 'video',
        )
        validated_data['calculation_version'] = validated_data.get(
            'calculation_version',
            'frontend_attention_v1',
        )

        with transaction.atomic():
            instance, _ = FaceAttentionSession.objects.update_or_create(
                user=user,
                session_id=session_id,
                defaults=validated_data,
            )

            if instance.is_assessment:
                if final_score is None:
                    final_score = round((instance.average_concentration_score / 8.0) * 100.0, 2)
                user.ai_assessment_score = final_score
                user.save(update_fields=['ai_assessment_score'])

            if instance.file and instance.file.is_management:
                progress_updated = ProgressTrackerActions.update_learning_progress(
                    user,
                    instance.file.file_type,
                    instance.file.day,
                    instance.file.order_number,
                )
                if not progress_updated:
                    raise ValidationError({
                        'file_id': 'Unable to update learning progress for this file.'
                    })

            if not instance.is_assessment:
                bump_user_management_cache(user.id)

        return instance
