from rest_framework import serializers
from apps.assessment.models import SelfAssessmentResponse,SelfAssessmentResult,SelfAssessmentQuestions
from apps.assessment.services.assessment_service import AssessmentService
from apps.filehandler.models import AdhdContent
from apps.progresstracker.models import (
    FaceAttentionSession,
    generate_attention_session_id,
)
from helpers.helper import get_token_user_or_none,get_object_or_none
from rest_framework.exceptions import ValidationError
import math


"""Self Assessment Serializers"""


"""Self Assessment Serializers"""

class SelfAssessmentSubSerializer(serializers.ModelSerializer):
    question        = serializers.IntegerField(allow_null=True, required=False)
    response        = serializers.ChoiceField(choices=SelfAssessmentResponse.RESPONSE_CHOICES.choices,allow_null=True, required=False)
    text_response   = serializers.CharField(allow_null=True, required=False)

    class Meta:
        model = SelfAssessmentResponse
        fields = ['id','question','response','text_response']

    def validate(self,attrs):
        return super().validate(attrs)
    
    def create(self,validated_data):
        result_instance = self.context.get('result_instance',None)

        question_instance = get_object_or_none(SelfAssessmentQuestions,pk=validated_data.get('question'))
        if question_instance is None:
            raise ValidationError({'question': 'Invalid question id.'})

        instance = SelfAssessmentResponse.objects.filter(result_entry=result_instance,question=question_instance).first()

        if instance:
            # Silently ignore to prevent 400 error when frontend sends already answered questions
            return instance

        instance                = SelfAssessmentResponse()
        instance.result_entry   = result_instance
        instance.question       = question_instance
        instance.response       = validated_data.get('response')
        instance.text_response  = validated_data.get('text_response',None)
        instance.save()

        return instance


class SelfAssessmentResponseSerializer(serializers.ModelSerializer):
    assesment   = serializers.ListField(child=SelfAssessmentSubSerializer(),allow_empty=False)

    class Meta:
        model = SelfAssessmentResult
        fields = ['assesment']


    def validate(self, attrs):
        return super().validate(attrs)


    def create(self, validated_data):
        request = self.context.get('request',None)

        assessment_results = validated_data.get('assesment',[])
        user_instance = get_token_user_or_none(request)


        instance = AssessmentService.get_or_create_result_for_user(user_instance)

        for results in assessment_results:
            sub_serializer = SelfAssessmentSubSerializer(data=results,context={'request':request,'result_instance':instance})
            sub_serializer.is_valid(raise_exception=True)
            sub_serializer.save()

        is_adult = bool(user_instance.adult)

        instance = AssessmentService.calculate_result(instance, is_adult)

        return instance


class FiniteFloatField(serializers.FloatField):
    def to_internal_value(self, data):
        value = super().to_internal_value(data)
        if not math.isfinite(value):
            raise ValidationError('A finite number is required.')
        return value


class FrontendAttentionScoreSerializer(serializers.Serializer):
    # The attention score is generated by the frontend and stored as
    # self-reported telemetry; backend validation only checks shape/ranges.
    session_id = serializers.CharField(required=False, allow_blank=False, max_length=100)
    file_id = serializers.PrimaryKeyRelatedField(
        source='file',
        queryset=AdhdContent.objects.all(),
        required=True,
        allow_null=False,
    )
    is_assessment = serializers.BooleanField(required=True)
    final_score = FiniteFloatField(required=True, min_value=0, max_value=100)
    attention_engagement_rate = FiniteFloatField(required=True, min_value=0, max_value=100)
    average_confidence = FiniteFloatField(required=True, min_value=0, max_value=1)
    total_processed_frames = serializers.IntegerField(required=True, min_value=0)
    sampled_frames = serializers.IntegerField(required=True, min_value=0)
    session_duration_seconds = FiniteFloatField(required=True, min_value=0)
    inattention_duration = FiniteFloatField(required=True, min_value=0)
    gaze_ratio_avg = FiniteFloatField(required=True, min_value=0, max_value=1)
    drowsy_state = FiniteFloatField(required=True, min_value=0, max_value=1)
    brightness_score = FiniteFloatField(required=True, min_value=0, max_value=100)
    pitch = FiniteFloatField(required=True, min_value=-180, max_value=180)
    yaw = FiniteFloatField(required=True, min_value=-180, max_value=180)
    roll = FiniteFloatField(required=True, min_value=-180, max_value=180)
    blink_ratio = FiniteFloatField(required=True, min_value=0)
    yawn_distance = FiniteFloatField(required=True, min_value=0)
    bad_frame_count = serializers.IntegerField(required=True, min_value=0)
    blurry_frame_count = serializers.IntegerField(required=True, min_value=0)
    low_light_frame_count = serializers.IntegerField(required=True, min_value=0)
    eyes_closed_count = serializers.IntegerField(required=True, min_value=0)
    gaze_warning_count = serializers.IntegerField(required=True, min_value=0)

    def validate(self, attrs):
        unknown_fields = set(self.initial_data.keys()) - set(self.fields.keys())
        if unknown_fields:
            raise ValidationError({
                field: 'Unknown field.' for field in sorted(unknown_fields)
            })

        expected_average_score = round((attrs['final_score'] / 100.0) * 8.0, 2)
        attrs['average_concentration_score'] = expected_average_score
        attrs['concentration_score'] = expected_average_score

        if attrs['sampled_frames'] > attrs['total_processed_frames']:
            raise ValidationError({
                'sampled_frames': 'Cannot exceed total_processed_frames.'
            })

        if attrs['inattention_duration'] > attrs['session_duration_seconds']:
            raise ValidationError({
                'inattention_duration': 'Cannot exceed session_duration_seconds.'
            })

        return attrs

    def create(self, validated_data):
        # User ownership is always taken from the authenticated JWT user.
        # Clients must not choose or spoof a user_id in telemetry payloads.
        user = self.context['request'].user
        final_score = validated_data.pop('final_score', None)
        session_id = validated_data.get('session_id') or generate_attention_session_id()
        validated_data['session_id'] = session_id
        instance, _ = FaceAttentionSession.objects.update_or_create(
            user=user,
            session_id=session_id,
            defaults=validated_data,
        )

        if instance.is_assessment:
            if final_score is None:
                final_score = round((instance.average_concentration_score / 8.0) * 100.0, 2)
            user.ai_assessment_score = final_score
            user.save(update_fields=['ai_assessment_score'])

        return instance
