# Generated by Django 5.2 on 2026-08-12
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='ProgramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=255, unique=True)),
                ('notification_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('newly_unlocked_day', models.PositiveIntegerField()),
                ('pending_activity_count', models.PositiveIntegerField(default=0)),
                ('pending_days', models.JSONField(default=list)),
                ('target_screen', models.CharField(max_length=100)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'ProgramNotification'},
        ),
        migrations.AddIndex(
            model_name='programnotification',
            index=models.Index(fields=['user', 'notification_type', 'newly_unlocked_day'], name='program_notice_user_day_idx'),
        ),
    ]
