# Generated by Django 5.2.14 on 2026-06-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhdContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(upload_to='adhd_content/', verbose_name='File')),
                ('is_management', models.BooleanField(default=False, help_text='True for Management files, False for Assessment files', verbose_name='Is Management')),
                ('age_group', models.CharField(choices=[('child', 'Child'), ('adolescents', 'Adolescents'), ('adult', 'Adult')], default='adult', max_length=50, verbose_name='Age Group')),
                ('day', models.IntegerField(blank=True, help_text='Required for management files. e.g. 1 for day-1', null=True, verbose_name='Day')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('file', 'File')], default='video', max_length=50, verbose_name='File Type')),
                ('order_number', models.IntegerField(default=1, verbose_name='Order Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'ADHD Content',
                'verbose_name_plural': 'ADHD Contents',
                'db_table': 'AdhdContent',
                'ordering': ['is_management', 'age_group', 'day', 'order_number'],
            },
        ),
    ]
